#!/bin/sh
logger "Trigger BTN_1 $ACTION"

export lock=/tmp/adblock-lock
export LED=/sys/devices/platform/leds-gpio/leds/gl-inet:red:adblock
export timeout=600


if [ "$ACTION" == "pressed" ];then
	if [ -f $lock ];then
		logger "killing sleep to finish last script"
		killall sleep
		exit 0
	fi

	touch $lock
	. "/usr/share/libubox/jshn.sh"

	json_load "$(cat /tmp/adb_runtime.json)"
	json_select data
	json_get_var value "adblock_status"
	logger "button pressed with $value"
	if [ "$value" == enabled ];then
		echo timer > $LED/trigger
		logger "suspend adblock for $timeout secs"
		/etc/init.d/adblock suspend
		(logger "resume adblock after $timeout";
		sleep $timeout;
		/etc/init.d/adblock resume;
		# TODO: trigger netdev
		echo default-on > $LED/trigger;
		rm $lock )&
	fi

fi
