#!/bin/sh

uci -q batch <<-EOT
	set adblock.global.adb_enabled='1'
	set adblock.adguard.enabled='1'
	set adblock.malware.enabled='1'
	set adblock.malwarelist.enabled='1'
	set adblock.openphish.enabled='1'
	set adblock.ransomware.enabled='1'
	commit
    EOT
